### ISSUE TITLE
Datenmodell anstatt SQL-Datei

### ISSUE THREAD

**Issue by britzke** [timtreibmann/JobTicket#10]
Zum Aufsetzen der Software wird die SQL-Datei nicht benötigt. Beim Start der Applikation prüft JPA das Vorhandensein der Tabellen in der angegebenen Datenbank. Sind die Tabellen nicht vorhanden, so werden sie automatisch angelegt.
Die Datenbankstruktur ist in den Entity-Beans kodiert.
Um die Datenbank weiterentwickeln zu können, ist es sinnvoller, das Datenmodell im Repository zu veröffentlichen. Es ist jedoch nicht sinnvoll, beides (SQL und Modell) im Repository zu speichern, da dies eine Redundanz verursacht, und zu Fehlern führen kann, wenn nicht beide Dateien manuell synchron gehalten werden.

**Comment by mueller-jan** [comment]
SQL-Datei gelöscht
