### ISSUE TITLE
Anmeldung der Mitarbeiter

### ISSUE THREAD

**Issue by olafzieger** [timtreibmann/JobTicket#11]
Es muss den Mitarbeitern möglich sein sich mit Benutzernamen und Passwort anzumelden und NUR seine Jobs zu sehen.

**Comment by britzke** [comment]
Die Anmeldung sollte über den zentralen Anmeldeserver von Runze&Casper funktionieren. Getestet kann die Funktion auch erst einmal mit der Tomcat-eigenen Benutzerdatenbank.

**Comment by mueller-jan** [comment]
Ergänzung: die Zeile:"Realm className="org.apache.catalina.realm.MemoryRealm"" muss in der server.xml unter dem Engine-Tag stehen.
