### ISSUE TITLE
encoding problem

### ISSUE THREAD

**Issue by olafzieger** [timtreibmann/JobTicket#13]
ich will euch ja nicht ärgern aber es gibt da ein Zeichenkodierungs-Problem. 
siehe Screenshot
![bildschirmfoto 2013-07-04 um 14 29 07](https://f.cloud.github.com/assets/2371334/749263/a65df416-e4a5-11e2-9bd6-c6e553fe72ca.png)

**Comment by mueller-jan** [comment]
Wir haben uns gestern mal mit dem Fehler beschäftigt und ihn leider nicht beseitigen können. Auf vielen Seiten wird empfohlen, einen Servlet-Filter zu schreiben: http://forum.primefaces.org/viewtopic.php?f=8&t=19925 . Leider hat das den Fehler auch nicht behoben. Er tritt immer auf, wenn ein Seitenwechsel per POST-Request stattfindet, aber nicht bei einem GET-Request.

**Comment by britzke** [comment]
Wie sehen die http Header aus?

**Comment by mueller-jan** [comment]
Nach einem Klick auf "Weiter" (p:commandbutton ajax="false) und auf der nächsten Seite auf "Zurück" (p:button) sieht der Header so aus:

![image](https://f.cloud.github.com/assets/4717779/818483/d1bbf26c-ef94-11e2-9134-49f20282e0d9.png)

Wenn man anstelle des p:commandButtons einen p:button nimmt, sehen die Buchstaben vernünftig aus.

**Comment by britzke** [comment]
Das sieht aus, als ob der UTF 8 kodierte Header als iso8859 interpretiert wird. Was steht denn in der Datenbank?

**Comment by mueller-jan** [comment]
Da steht's richtig drin. 
![unbenannt](https://f.cloud.github.com/assets/4717779/818587/525d88c4-ef98-11e2-90f7-57b58e436723.png)

**Comment by britzke** [comment]
Wie sieht es aus wenn das encodier des Browsers umgestellt wird auf UTF 8?

**Comment by mueller-jan** [comment]
Der ist schon auf UTF-8 eingestellt.

**Comment by mueller-jan** [comment]
Könnte das Problem etwas hiermit zutun haben: https://community.jboss.org/thread/230605 ?

**Comment by mueller-jan** [comment]
Problem gefunden Weld 2.siehe https://issues.jboss.org/browse/WELD-1467
Workaround: weld auf 1.10 downgraden
