### ISSUE TITLE
Quelltext kommentieren

### ISSUE THREAD

**Issue by timtreibmann** [timtreibmann/JobTicket#17]

**Comment by timtreibmann** [comment]
Quelltext wurde kommentiert

**Comment by timtreibmann** [comment]
Ich überarbeite die kommentierung dann bei Zeiten nochmal

**Comment by britzke** [comment]
:-) bei welchen Zeiten?

**Comment by timtreibmann** [comment]
wenn ich ein besseres plugin gefunden habe!

**Comment by britzke** [comment]
hört sich nicht so gut an :-(

**Comment by britzke** [comment]
Am besten es gilt die Regel: Jede Methode, die verändert oder neu implementiert wird, erhält eine adäquate JAVADOC Dokumentation.

**Comment by timtreibmann** [comment]
ich werd zu allen methoden nochmal einen text schreiben und auch die klassen besser erläutern - sitzt gerade am css und die vordefinierten primefaces button rauben recht viel zeit

**Comment by britzke** [comment]
ich kann ein lied davon singen!
