### ISSUE TITLE
CSS unklar wie Elemente erreicht werden können

### ISSUE THREAD

**Issue by timtreibmann** [timtreibmann/JobTicket#27]
Mir ist bei den markierten Elementen unklar wie ich sie im css ansprechen soll - bis jetzt hat mich eine ausgiebige firebug suche nicht weitergebracht
![bugcss](https://f.cloud.github.com/assets/4717799/778598/cd0a7d8c-e9b4-11e2-8f80-136ff3b4b6cf.png)

**Comment by britzke** [comment]
da haben Sie ja mit Ihrem Screenshot viel weiße Fläche in den Issue geladen.

**Comment by britzke** [comment]
css bietet den nth-child(n) pseudo selector an. damit kann man da n-te child eines element adressieren. 'n' ist frei wählbar.
