### ISSUE TITLE
Sortierfunktion für Kunden- und Mitarbeiterliste

### ISSUE THREAD

**Issue by mueller-jan** [timtreibmann/JobTicket#34]
Die Kunden und Mitarbeiter sollen sortiert/gefiltert werden können.

**Comment by mwanka** [comment]
Entweder ist die Fortschrittssortierung noch leicht fehlerhaft oder die Fortschritts-prozentanzeige.

Edit: Es wurde nur die falsche variable abgefragt, erledigt.
