### ISSUE TITLE
Jobbeschreibung und evtl. Jobname entfernen

### ISSUE THREAD

**Issue by mueller-jan** [timtreibmann/JobTicket#37]
Die Inputfelder "Jobname" und "Jobbeschreibung" sollen aus der jobticket_main.xhtml entfernt werden.

**Comment by klausguenther** [comment]
Jobname wäre eine wichtige Information.

Der Jobname setzt sich meist (nicht automatisch) aus der Jobnummer, dem Kundenkürzel und dem Produkt zusammen. Bsp: 09012_R&C_Jobticket  :-)

**Comment by britzke** [comment]
So einen Jobnamen könnte man ggf. aus anderen Informationen (Datum/Uhrzeit oder Kundenkürzel) zusammensetzen. Welche Regel gibt es da? Kann man die Regel evtl. verallgemeinern?  Eine variable Umsetzung könnte hier sinnvoll sein - gg.f eine MikroDSL in der Art: "{d.getYear()+d.getMonth()+'_'+kundenkürzel}"
