### ISSUE TITLE
ändern des Themes geht nicht Error loading theme.css …

### ISSUE THREAD

**Issue by olafzieger** [timtreibmann/JobTicket#41]
Ich wollte mal ein anderes Theme auswählen und jetzt komme ich nicht mehr anmelden. Aber vor dem fixen müssen wir bestimmt was zahlen ;-) Oder?

Error loading theme, cannot find "theme.css" resource of "primefaces-" library

viewId=/login.xhtml
location=/Library/Tomcat/webapps/JobTicket/login.xhtml
phaseId=RENDER_RESPONSE(6)

Caused by:
javax.faces.FacesException - Error loading theme, cannot find "theme.css" resource of "primefaces-" library
at org.primefaces.renderkit.HeadRenderer.encodeTheme(HeadRenderer.java:130)
![bildschirmfoto 2013-08-21 um 12 19 04](https://f.cloud.github.com/assets/2371334/1000478/8514567a-0a4c-11e3-97cb-c6076a9fce0a.png)

**Comment by timtreibmann** [comment]
bin zwar gerade krank :(
aber könntest du das problem bzw den ablauf noch etwas genauer beschreiben dann schau ichs mir mal an 
was genau hast du gemacht? konntest du vorher themes auswählen? ist das nur bei dir so?

**Comment by olafzieger** [comment]
Hallo Tim,
mach dir keinen Stress werd erst mal gesund.
1. also ich hatte versucht nach meinem Login unter Optionen das Layout (Theme) zu wechseln. Danach konnte sich erstmal keiner mehr anmelden. 
![bild 1](https://f.cloud.github.com/assets/2371334/1007949/f6f06176-0b14-11e3-8a3f-943bad9c43c8.png)

2 - dann habe ich mir gedacht ich starte mal den Tomcat neu 

![bildschirmfreigabebild 22 august 2013 12 17 33 mesz](https://f.cloud.github.com/assets/2371334/1007953/1ff2ffac-0b15-11e3-9ce1-bd60fbeeaad2.png)

3 - danach konnten sich alle wieder anmelden aber scheinbar ist die Datenbank weggeflogen. Soll ich dir eine Logdatei schicken? Und wen ja wo finde ich diese?

![bild 2](https://f.cloud.github.com/assets/2371334/1007967/9ada9702-0b15-11e3-89d2-bb5a9474591b.png)

**Comment by olafzieger** [comment]
ist das diese hier?

![bildschirmfreigabebild 22 august 2013 12 31 32 mesz](https://f.cloud.github.com/assets/2371334/1007985/4442ec22-0b16-11e3-8f4a-4f23d84f665a.png)

**Comment by timtreibmann** [comment]
hm das die datenbank weg ist, verwundert mich. die datenbank läuft zwar embedded aber die daten der datenbank sollten eigentlich sepperat gespeichert werden. ich glaube wir hatten den pfad so angelegt, dass die datenbank auf dem desktop gespeichert wird (vll nicht optimal). 
der fehler, dass die theme.css nich gefunden werden kann, deutet nach meinen recherchen darauf hin, dass der classpath nicht mehr aktuell ist. die frage die ich mir stelle ist halt, warum? wenn du zeit hast schick mir mal den ganzen config ordner, dann wurschtel ich mich da durch.

ich mein den ordner den du im bild angewählt hast (conf) mit allen datein context logging server usw

**Comment by olafzieger** [comment]
Oh … da hatte ich vorhin etwas gelöscht was so aussah, ich dachte das war noch von der Tomcat installation liegengeblieben 
ich schau mal ob es noch im TimeMachine-Backup zu finden ist

**Comment by olafzieger** [comment]
ich schick dir mal den conf-Ordner per mail

**Comment by mueller-jan** [comment]
Ich habe zuhause mal einen Tomcat-Server eingerichtet und über zwei Rechner ausprobiert, das Theme zu ändern und konnte den Fehler nicht reproduzieren. Wir können ja den Themechanger erst mal wieder rausnehmen.

Gab es eigentlich nochmal Probleme mit der Datenbank? Wird da ein Ordner auf dem Schreibtisch erzeugt? Wenn nicht, müsste man mal gucken, was für ein Speicherort für die Datenbank in der "context.xml" im Verzeichnis "Tomcat\webapps\JobTicket\META-INF" angegeben ist.

Wenn du Zeit und Lust hast, kannst du uns auch noch den Ordner "logs" aus dem Tomcat-Verzeichnis schicken.

**Comment by britzke** [comment]
bitte nicht den Theme-Changer 'rausnehmen! Der ist so gut! Ich bin am Montag vor Ort – dann kläre ich das!

**Comment by britzke** [comment]
Da es sich um eine Test-Installation handelt, konnte ich die Datenbank einfach ersetzen durch eine neue. Damit ist das Problem gelöst. Wahrscheinlich lag der Fehler nicht an der Umstellung des Themas, sondern an dem UNTERDEMHINTERNWEGZIEHEN der Datenbank.
