### ISSUE TITLE
Jobfilter anpassen

### ISSUE THREAD

**Issue by olafzieger** [timtreibmann/JobTicket#42]
Bitte die Filteroptionen, nach dem Login, nicht wie im Screenshot auf Mitarbeiter auswählen setzen. Vielleicht besser zunächst ohne Filter starten und eine Filterdirekteingabe neben dem Optionsbutton. Der Benutzer ist verwirrt und denkt die Datenbank ist enthält keine Jobs. 
![bildschirmfoto 2013-10-28 um 18 11 42](https://f.cloud.github.com/assets/2371334/1421955/91545272-3ff4-11e3-8b5c-8c12d1108a89.png)
![bildschirmfoto 2013-10-28 um 18 11 31](https://f.cloud.github.com/assets/2371334/1421977/e34244ea-3ff4-11e3-837c-9361e6ea306e.png)

**Comment by olafzieger** [comment]
> Vielleicht besser zunächst ohne Filter starten und eine Filterdirekteingabe neben dem Optionsbutton.

Ist diese Anpassung sehr schwer umzusetzen? Mitarbeiter denken immer die Datenbank wäre lehr.

**Comment by mueller-jan** [comment]
Sorry, Ich habe den Issue übersehen. Das wäre eigentlich eine Arbeit von 5 Minuten gewesen.

Der Mitarbeiterfilter kann auf jeden Fall neben den Options-Button gesetzt werden.
Außerdem könnte man ja die Häkchen-Option für "Jobs nach Mitarbeitern filtern" entfernen und im Dropdown-Menu einen Eintrag für "Alle Benutzer" hinzufügen. Wenn Tickets für den eingeloggten Benutzer vorhanden sind, wird dann der entsprechende Benutzer ausgewählt, ansonsten wird der Eintrag "Alle Benutzer" ausgewählt.

**Comment by olafzieger** [comment]
Super das ist schön. Wenn du mal wieder zu uns kommen magst Ruf einfach kurz an.

**Comment by mueller-jan** [comment]
Die Mitarbeiterfilter-Eingabe befindet sich jetzt auf der Startseite.
