### ISSUE TITLE
unschöner Layoutfehler

### ISSUE THREAD

**Issue by olafzieger** [timtreibmann/JobTicket#44]
![bildschirmfoto 2013-10-28 um 18 32 46](https://f.cloud.github.com/assets/2371334/1422186/7896ef44-3ff7-11e3-9fa2-60ca7a434d8a.png)

**Comment by olafzieger** [comment]
Fehler ist noch nicht behoben

![bildschirmfoto 2013-12-13 um 13 06 22](https://f.cloud.github.com/assets/2371334/1741944/1114034a-63ef-11e3-9756-7b1fdcb4fdce.png)

**Comment by timtreibmann** [comment]
Danke für das Feedback. Wir haben eure Anfrage wahrgenommen. Bitte gebt uns etwas mehr Zeit. Wir haben zur Zeit und in naher Zukunft sehr viel zu tun. Stichwort Abschlussklausuren.
