### ISSUE TITLE
Job Ticket Filter Fehlerhaft

### ISSUE THREAD

**Issue by ulrich-gatz** [timtreibmann/JobTicket#45]
Der Filter scheint den Benutzernamen nicht richtig zu verarbeiten.

Bei ausgewähltem Benutzernamen werden Jobs die von Ihm erstellt sind nicht angezeigt. Erst nach deaktivierung des Filters werden die Jobs angezeigt.

![bildschirmfoto 2013-12-13 um 12 48 25](https://f.cloud.github.com/assets/6177993/1741857/c2b3ff0e-63ec-11e3-8803-fb5ae4fa33f7.png)

![bildschirmfoto 2013-12-13 um 12 48 41](https://f.cloud.github.com/assets/6177993/1741860/c6e60f40-63ec-11e3-9205-80096e6e3f99.png)

**Comment by ulrich-gatz** [comment]
Kannst Du mich als contributor hinzufügen. 
Ich bin  Ulrich Gatz von R&C

**Comment by timtreibmann** [comment]
Hab dich als Collaborator hinzugefügt.

**Comment by mueller-jan** [comment]
Ich hab's gerade nochmal ausprobiert und konnte den Fehler nicht reproduzieren.

Zur Zeit ist es so, dass der am Ticket arbeitende Angestellte noch mit einem Buttonklick hinzugefügt werden muss - was vielleicht etwas umständlich ist. Vielleicht wäre es besser, den Ticketersteller automatisch auch als Ticketbearbeiter hinzuzufügen. Nur gibt es ja manchmal auch Ticketersteller, die es nicht selbst bearbeiten.
![image](https://f.cloud.github.com/assets/4717779/1757363/5ba41a8e-667f-11e3-99e0-e92fbcfd405c.png).

**Comment by britzke** [comment]
Vielleicht könnte ein Häkchen bei der Ticket-Erstellung angeben, ob der Ersteller auch gleichzeitig bearbeitet ist, etwa so wie "[ ] Ticket mir zuordnen"

**Comment by olafzieger** [comment]
Der Filter scheint aber jetzt richtig zu greifen, siehe screenshot.
Es werden bei der Auswahl des Mitarbeiter-Filters auch dessen Jobs gezeigt.

![bildschirmfoto 2014-02-03 um 14 36 25](https://f.cloud.github.com/assets/2371334/2064984/e9bfe7ec-8cd8-11e3-8981-9ed1ebeb1a51.png)

**Comment by olafzieger** [comment]
> Vielleicht könnte ein Häkchen bei der Ticket-Erstellung angeben, ob der Ersteller auch gleichzeitig bearbeitet ist, etwa so wie "[ ] Ticket mir zuordnen"

Kann dieser Issue geschlossen werden? Oder soll er weiter offen bleiben wegen diesem Vorschlag von Burghard?

**Comment by mueller-jan** [comment]
Es ist jetzt so umgesetzt, dass beim Erzeugen eines neuen Tickets automatisch der Ticket-Ersteller
dem Job zugeordnet wird (wenn ein Mitarbeiter in der Datenbank existiert, der mit dem Login-Namen des angemeldeten Benutzers verknüpft ist) .

Zur Not kann ja der automatisch hinzugefügte Mitarbeiter per Klick auf das Mülleimer-Icon wieder entfernt werden. Finde das eigentlich so ganz gut.

**Comment by britzke** [comment]
Einen Mitarbeiter per Klick auf die Mülltonne entfernen? Krasse Metapher! :-)

bubi@iBad

**Comment by olafzieger** [comment]
Oh nein ich hoffe nicht das es bei mir bald klickt. Man weis ja nie. 
;-/
