### ISSUE TITLE
Benutzerdatenbank erforderlich

### ISSUE THREAD

**Issue by olafzieger** [timtreibmann/JobTicket#46]
Bitte eine User-Datenbank anlegen oder unser Hausinternes Active Directory nutzen. Wir müssen jetzt selbst Benutzer verwalten können.

**Comment by britzke** [comment]
Falls sich niemand sonst findet...

**Comment by olafzieger** [comment]
Ich habe in der xml-datei neue Benutzer ergänzt. Die beiden Entwickler können ja bei Uli mal anfragen wegen der Einbindung des Active Directory. Schöner wäre diese Lösung ja.

**Comment by mueller-jan** [comment]
Hallo, 
hab auf jeden Fall Interesse dran weiterzuarbeiten. Hatte nur bis jetzt auch ziemlich viel um die Ohren.

**Comment by britzke** [comment]
Dieser Issue ist ein Doppel von #11. Deshalb schlage ich vor, diesen Fall zu schließen und alle weiteren Diskussionen unter #11 fortzusetzen
