### ISSUE TITLE
Für die Nutzung der Software und die Weiterentwicklung sollte ein Lizenzmodell gefunden werden

### ISSUE THREAD

**Issue by britzke** [timtreibmann/JobTicket#47]
Um Nutzern und Entwicklern Rechtssicherheit zu gewähren, sollte ein Lizenzmodell für dieses Projekt gefunden werden. Der Vorschlag als Lizenzmodell die _General Public License_ (GPL V3) zu verwenden steht hierbei seit einiger Zeit bereits im Raum.

**Comment by timtreibmann** [comment]
Ich stimme ihrem Vorschlag zu. Wenn Jan der gleichen Meinung ist, könnten wir die Implementierung in Angriff nehmen.

**Comment by mueller-jan** [comment]
Ich bin auch einverstanden.
