### ISSUE TITLE
JobTicket auf Olafs Mac einrichten

### ISSUE THREAD

**Issue by olafzieger** [timtreibmann/JobTicket#5]
Könntet Ihr Morgen im Büro sein und mir Kurz helfen das Projekt JT in meiner IDE einzurichten Sodas wir hier immer mal schauen können wie weit ihr seit.

Grußn Olaf Zieger

**Comment by timtreibmann** [comment]
geht klar

---

 Von: olafzieger notifications@github.com
An: timtreibmann/JobTicket JobTicket@noreply.github.com 
CC: timtreibmann melusinesportal@yahoo.de 
Gesendet: 13:21 Mittwoch, 26.Juni 2013
Betreff: [JobTicket] JobTicket auf Olafs Mac einrichten (#5)

Könntet Ihr Morgen im Büro sein und mir Kurz helfen das Projekt JT in meiner IDE einzurichten Sodas wir hier immer mal schauen können wie weit ihr seit.
Grußn Olaf Zieger

**Comment by olafzieger** [comment]
Olaf Zieger benötigt Hilfe beim synchronisieren des Git-Repository, da er euren Code nicht kennt.
