### ISSUE TITLE
Tomcat kommt mit https nicht klar

### ISSUE THREAD

**Issue by olafzieger** [timtreibmann/JobTicket#50]
Hallo,

erstmal vielen Dank für eure tolle Software. Was kann man machen das der Tomcat mit https klar kommt? Unser Server läuft ab jetzt nur noch sichere Verbindungen.

Vielen Dank! 

![bildschirmfoto 2014-04-25 um 10 07 13](https://cloud.githubusercontent.com/assets/2371334/2798588/e70d9a7c-cc51-11e3-9604-bb4fcb3d9470.png)

**Comment by britzke** [comment]
Man muss den Connection rochtig konfigurieren, vor allem das Zertifikat in den keystore importieren. 

burghard@iSir

**Comment by olafzieger** [comment]
man eine Baustelle zu dann gleich die neue wieder auf, mist ;-( 

Am 25.04.2014 um 12:15 schrieb burghard.britzke notifications@github.com:

**Comment by olafzieger** [comment]
Kannst du so was Burghard?

**Comment by britzke** [comment]
:-)

Am 25.04.2014 um 14:27 schrieb olafzieger notifications@github.com:

**Comment by britzke** [comment]
Auf dem Server muss die URL mit localhost angegeben werden. Auf anderen Rechnern funktioniert die  URL ohne https.
