### ISSUE TITLE
Mitarbeiter sollen aus dem LDAP gelesen werden

### ISSUE THREAD

**Issue by ulrich-gatz** [timtreibmann/JobTicket#55]
Zur Zeit werden die Mitarbeiter, die in JobTickets vermerkt sind, aus der Datenbank gelesen. Es existiert in der Firma jedoch schon ein Verzeichnis für die Mitarbeiter (Active Directory).
Um doppelte Datenpflege zu verhindern, sollten die Mitarbeiter aus dem Mitarbeiter-Verzeichnis gelesen werden.

**Comment by mwanka** [comment]
Ich habe heute angefangen mich mit diesem Issue auseinander zu setzen und bin mir noch nicht so sicher ob wir die nötigen Daten direkt beim Anmelden(wo der AD bereits verknüpft ist) bekommen können, oder ob wir noch eine 2te resource-Datenbank Verknüpfung brauchen um Vor- und Nachnamen vom AD zu bekommen.

**Comment by britzke** [comment]
Am besten wäre es, wenn die Daten zu dem Zeitpunkt aus dem Verzeichnis geholt werden, wenn das Formular angezeigt werden soll. So erhält man immer die aktuelle Liste von Mitarbeitern. Das Abrufen der Mitarbeiter ist performant genug, um es häufiger durchzuführen.
