### ISSUE TITLE
Stundenauswertung für Jobs

### ISSUE THREAD

**Issue by ulrich-gatz** [timtreibmann/JobTicket#56]

**Comment by mwanka** [comment]
Es gibt nun eine grafische Auswertung, wobei noch besprochen werden muss ob die so ausreicht oder noch andere Features gewünscht werden.

**Comment by britzke** [comment]
Welches Framework wurde für die grafische Auswertung verwendet? Es gibt eine Liste für einen guten Überblick über vorhandene Frameworks unter http://java-source.net/open-source/charting-and-reporting

**Comment by mwanka** [comment]
Primefaces, bringt verschiedene charts mit ich habe mich für das pieChartModel entschieden aber es gibt auch linienDiagramme

**Comment by mwanka** [comment]
Wird nun in #59 weiterbehandelt. 
Closed.
