### ISSUE TITLE
Fortschrittsanzeige ändern

### ISSUE THREAD

**Issue by mwanka** [timtreibmann/JobTicket#58]
Fortschritt soll nichtmehr in % angezeigt werden, sondern wieviel der Produkte fertig sind.

**Comment by olafzieger** [comment]
Hallo Marcus,

bei unserem JobTicket App besteht Bedarf Funktionen zu ergänzen.
Bitte melde dich doch mal bei Ulrich Gatz um zu besprechen wie wir vorgehen.
Hier der Kontakt:
Ulrich Gatz
gatz@runze-casper.de
T ++49/30/28018-172

Vielen Dank!

Mit freundlichen Grüßen

Olaf Zieger

Runze & Casper Werbeagentur GmbH
Linienstraße 214
D-10119 Berlin
T ++49/30/28018-190
F ++49/30/28018-300

Geschäftsführer:
Andreas Runze, Carl Michael Casper
Amtsgericht Berlin Charlottenburg
HR B 25 585

Am 07.07.2014 um 15:25 schrieb MarcusWanka notifications@github.com:

**Comment by britzke** [comment]
hat er sich gemeldet? Ich sehe ihn morgen (wenn er nicht fehlt, was selten ist).
Gruß
burghard.

Am 14.10.2014 um 15:47 schrieb olafzieger notifications@github.com:

**Comment by olafzieger** [comment]
Nein noch nicht. Er soll aber Uli anrufen. Ich hab ja schon wieder Urlaub. 

Bye olaf
