### ISSUE TITLE
TableBean nicht notwendig

### ISSUE THREAD

**Issue by britzke** [timtreibmann/JobTicket#9]
mit Commit 9f94650 wurde die Klasse TableBean dem Projekt hinzugefügt, die Übersetzungsfehler wegen einer Referenz zur Klasse Car verursacht. Da die Klasse offensichtlich nur Testzwecken dient sollte sie aus dem Repository entfernt werden.

**Comment by mueller-jan** [comment]
tablebean gelöscht
